[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.11.0"

[functions]
  included_files = ["data.json"]
  node_bundler = "esbuild"

[[plugins]]
  package = "./plugins/netlify-plugin-publish-masto"
